// Auto-generated from Livestock_Breed_Master 01.xlsx (Breed Master). Do not hand-edit.
// Ranges are ICAR/NBAGR-type textbook averages; engine uses locked singles.
export type LivestockSpecies = 'Cattle' | 'Buffalo' | 'Sheep' | 'Goat' | 'Pig' | 'Poultry' | 'Horse';
export interface BreedRecord {
  id: string; species: LivestockSpecies; breed: string; origin: string;
  maleWtKg: string; femaleWtKg: string; singleTwinPct: string;
  purposes: string; suitableClimate: string; note: string;
}
export const SPECIES_MASTER: LivestockSpecies[] = ['Cattle', 'Buffalo', 'Sheep', 'Goat', 'Pig', 'Poultry', 'Horse'];
export const BREED_MASTER: BreedRecord[] = [
  { id: 'cattle-gir', species: 'Cattle', breed: 'Gir', origin: 'Gir forests, Junagadh, Bhavnagar - Gujarat', maleWtKg: '400-500', femaleWtKg: '300-350', singleTwinPct: '98/2', purposes: 'Milk', suitableClimate: 'Gujarat; hot, semi-arid tropical', note: 'Gir is a premier indigenous dairy breed known for its distinctive convex forehead and long pendulous ears. It is heat tolerant and used worldwide for crossbreeding to improve milk yield in tropical climates.' },
  { id: 'cattle-sahiwal', species: 'Cattle', breed: 'Sahiwal', origin: 'Sahiwal district (Montgomery), Punjab belt - Punjab/Haryana', maleWtKg: '400-500', femaleWtKg: '300-400', singleTwinPct: '98/2', purposes: 'Milk', suitableClimate: 'Punjab, Haryana; hot, semi-arid', note: 'Sahiwal is one of the best indigenous dairy breeds of India with a docile temperament and loose skin. It shows good heat and tick resistance, making it a preferred dam line for crossbreeding programmes.' },
  { id: 'cattle-red-sindhi', species: 'Cattle', breed: 'Red Sindhi', origin: 'Sindh region (now Pakistan); reared in Punjab, Karnataka, Kerala, TN', maleWtKg: '400-450', femaleWtKg: '300-350', singleTwinPct: '98/2', purposes: 'Milk', suitableClimate: 'Punjab, South India; hot, humid/arid', note: 'Red Sindhi is a compact, reddish-brown dairy breed noted for disease resistance and heat tolerance. It adapts well outside its native tract and is widely used in organised dairy farms of South India.' },
  { id: 'cattle-tharparkar', species: 'Cattle', breed: 'Tharparkar', origin: 'Tharparkar district - Rajasthan/Sindh border (desert tract)', maleWtKg: '400-450', femaleWtKg: '300-350', singleTwinPct: '98/2', purposes: 'Dual (Milk + Draught)', suitableClimate: 'Rajasthan (arid, desert)', note: 'Tharparkar is a hardy dual-purpose desert breed, white/grey in colour, well suited to scarce fodder and water. It is valued both for its moderate milk yield and its draught power under harsh arid conditions.' },
  { id: 'cattle-rathi', species: 'Cattle', breed: 'Rathi', origin: 'Bikaner, Ganganagar, Churu, Jaisalmer - Rajasthan', maleWtKg: '350-400', femaleWtKg: '250-300', singleTwinPct: '98/2', purposes: 'Milk', suitableClimate: 'Rajasthan (arid, north-western)', note: 'Rathi is a leading dairy breed of arid Rajasthan, developed by the Rath community of pastoralists. It is compact, brown-and-white, and gives comparatively good milk yield on sparse desert grazing.' },
  { id: 'cattle-kankrej', species: 'Cattle', breed: 'Kankrej', origin: 'Banaskantha, Kutch (Gujarat) and Barmer, Jalore (Rajasthan)', maleWtKg: '450-550', femaleWtKg: '350-400', singleTwinPct: '98/2', purposes: 'Dual (Milk + Draught)', suitableClimate: 'Gujarat, Rajasthan border; arid/semi-arid', note: 'Kankrej is a large, silver-grey draught-cum-dairy breed with lyre-shaped horns, one of the heaviest zebu breeds. Bullocks are prized for fast trotting and heavy cart/plough work in the Rann of Kutch region.' },
  { id: 'cattle-hariana', species: 'Cattle', breed: 'Hariana', origin: 'Rohtak, Hisar, Gurgaon, Jind - Haryana', maleWtKg: '400-450', femaleWtKg: '300-350', singleTwinPct: '98/2', purposes: 'Dual (Milk + Draught)', suitableClimate: 'Haryana, Delhi-NCR; semi-arid', note: 'Hariana is a white/grey dual-purpose breed of the Indo-Gangetic plains, valued for strong bullocks. It is medium in milk yield but highly regarded for agricultural draught power.' },
  { id: 'cattle-ongole', species: 'Cattle', breed: 'Ongole', origin: 'Ongole, Guntur, Prakasam - Andhra Pradesh', maleWtKg: '500-600', femaleWtKg: '350-400', singleTwinPct: '98/2', purposes: 'Draught (Breeder)', suitableClimate: 'Andhra Pradesh; hot, humid coastal', note: 'Ongole is a large, powerful, white draught breed exported globally (basis of Brahman/American breeds). Bullocks are massive with a prominent hump and are used mainly for heavy draught and breeding.' },
  { id: 'cattle-deoni', species: 'Cattle', breed: 'Deoni', origin: 'Latur, Bidar, Osmanabad - Maharashtra/Karnataka border', maleWtKg: '400-450', femaleWtKg: '300-350', singleTwinPct: '98/2', purposes: 'Dual (Milk + Draught)', suitableClimate: 'Maharashtra, Karnataka; semi-arid', note: 'Deoni is a black-and-white spotted dual-purpose breed of the Deccan plateau with drooping ears. It combines moderate milk yield with reasonably good draught ability in mixed farming systems.' },
  { id: 'cattle-nagori', species: 'Cattle', breed: 'Nagori', origin: 'Nagaur, Merta - Rajasthan', maleWtKg: '400-450', femaleWtKg: '300-330', singleTwinPct: '98/2', purposes: 'Draught', suitableClimate: 'Rajasthan; arid', note: 'Nagori is a tall, elegant white draught breed of Rajasthan famous for fast trotting bullocks. It is not a dairy breed and is reared almost exclusively for its superior gait and pulling power.' },
  { id: 'cattle-malvi', species: 'Cattle', breed: 'Malvi', origin: 'Malwa plateau - Ratlam, Ujjain, Mandsaur (Madhya Pradesh)', maleWtKg: '400-450', femaleWtKg: '300-330', singleTwinPct: '98/2', purposes: 'Draught', suitableClimate: 'Madhya Pradesh; sub-tropical', note: 'Malvi is a grey draught breed of the Malwa plateau developed for fast, agile bullock work. It has small horns and thrives on the black cotton soils typical of central India.' },
  { id: 'cattle-mewati-kosi', species: 'Cattle', breed: 'Mewati (Kosi)', origin: 'Alwar, Bharatpur (Rajasthan) and Mathura (UP)', maleWtKg: '400-450', femaleWtKg: '300-330', singleTwinPct: '98/2', purposes: 'Draught', suitableClimate: 'Rajasthan, Uttar Pradesh; semi-arid', note: 'Mewati is a sturdy grey-white draught breed reared by the Meo community of the Mewat region. It is prized for heavy cart and plough work rather than milk production.' },
  { id: 'cattle-gaolao', species: 'Cattle', breed: 'Gaolao', origin: 'Wardha, Nagpur, Chandrapur - Maharashtra', maleWtKg: '350-400', femaleWtKg: '250-300', singleTwinPct: '98/2', purposes: 'Draught', suitableClimate: 'Maharashtra, Madhya Pradesh; semi-arid', note: 'Gaolao is a small, white, fast-moving draught breed of the Vidarbha region with a compact body. Its bullocks are noted for speed and endurance in light cart work.' },
  { id: 'cattle-khillari', species: 'Cattle', breed: 'Khillari', origin: 'Solapur, Sangli (Maharashtra) and Bijapur (Karnataka)', maleWtKg: '400-450', femaleWtKg: '300-330', singleTwinPct: '98/2', purposes: 'Draught', suitableClimate: 'Maharashtra, Karnataka; semi-arid', note: 'Khillari is a grey, muscular draught breed of the Deccan famous for sturdy, active bullocks. It is well adapted to the dry, rocky terrain between the Bhima and Krishna rivers.' },
  { id: 'cattle-hallikar', species: 'Cattle', breed: 'Hallikar', origin: 'Mysore, Mandya, Hassan - Karnataka', maleWtKg: '400-450', femaleWtKg: '300-330', singleTwinPct: '98/2', purposes: 'Draught', suitableClimate: 'Karnataka; semi-arid plateau', note: 'Hallikar is a grey draught breed known for its alert temperament, long horns and quick movement. It forms the base stock of the famous Amrit Mahal breed developed by Mysore rulers for war/transport.' },
  { id: 'cattle-kangayam', species: 'Cattle', breed: 'Kangayam', origin: 'Coimbatore, Tirupur, Erode - Tamil Nadu', maleWtKg: '350-400', femaleWtKg: '250-300', singleTwinPct: '98/2', purposes: 'Draught', suitableClimate: 'Tamil Nadu; semi-arid', note: 'Kangayam is a compact grey-white draught breed used traditionally in Jallikattu bull-taming events. It is hardy, quick-tempered, and well suited to dry farming tracts of western Tamil Nadu.' },
  { id: 'cattle-vechur', species: 'Cattle', breed: 'Vechur', origin: 'Kerala (Vechur village, Kottayam)', maleWtKg: '150-180', femaleWtKg: '100-130', singleTwinPct: '98/2', purposes: 'Milk (Breeder)', suitableClimate: 'Kerala; hot, humid', note: 'Vechur is the world’s smallest cattle breed, a dwarf dairy animal listed as an endangered breed. Despite its small size it gives milk with high fat content and is conserved for genetic diversity.' },
  { id: 'buffalo-murrah', species: 'Buffalo', breed: 'Murrah', origin: 'Rohtak, Hisar, Jind - Haryana', maleWtKg: '500-600', femaleWtKg: '400-500', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Haryana, Punjab; semi-arid', note: 'Murrah is the best dairy buffalo breed of India, jet-black with tightly curled horns and highest milk yield. It is the most widely used breed for grading-up and crossbreeding buffalo populations across the country.' },
  { id: 'buffalo-nili-ravi', species: 'Buffalo', breed: 'Nili-Ravi', origin: 'Ravi river valley - Ferozepur, Punjab (also Pakistan Punjab)', maleWtKg: '550-650', femaleWtKg: '450-500', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Punjab; semi-arid', note: 'Nili-Ravi is a high-yielding dairy buffalo distinguished by its characteristic wall (blue) eyes and white markings. It rivals Murrah in milk production and is often used to further improve Murrah herds.' },
  { id: 'buffalo-bhadawari', species: 'Buffalo', breed: 'Bhadawari', origin: 'Agra, Etawah - Uttar Pradesh (Yamuna-Chambal ravines)', maleWtKg: '400-450', femaleWtKg: '350-400', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Uttar Pradesh; sub-tropical', note: 'Bhadawari is a small, copper-brown buffalo whose milk has the highest fat percentage among buffalo breeds. It is well adapted to the ravine terrain of the Chambal and Yamuna river tracts.' },
  { id: 'buffalo-jaffarabadi', species: 'Buffalo', breed: 'Jaffarabadi', origin: 'Gir forests, Junagadh, Amreli - Gujarat', maleWtKg: '550-650', femaleWtKg: '450-550', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Gujarat; hot, semi-arid', note: 'Jaffarabadi is the heaviest Indian buffalo breed with massive, drooping horns curling around the ears. It gives high milk yield per lactation and is well suited to the Gir forest grazing tracts.' },
  { id: 'buffalo-surti', species: 'Buffalo', breed: 'Surti', origin: 'Kaira (Kheda), Baroda - Gujarat', maleWtKg: '400-450', femaleWtKg: '350-400', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Gujarat; sub-humid', note: 'Surti is a medium-sized, sickle-horned buffalo known for good milk quality with high fat content. It is calm in temperament and popular among small dairy farmers of central Gujarat.' },
  { id: 'buffalo-mehsana', species: 'Buffalo', breed: 'Mehsana', origin: 'Mehsana, Sabarkantha - Gujarat', maleWtKg: '450-500', femaleWtKg: '400-450', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Gujarat; semi-arid', note: 'Mehsana buffalo originated from crossing Murrah with local Surti stock and is intermediate in size. It is a good dairy breed adapted to the semi-arid tracts of North Gujarat.' },
  { id: 'buffalo-nagpuri-elitchpuri', species: 'Buffalo', breed: 'Nagpuri (Elitchpuri)', origin: 'Nagpur, Akola, Amravati - Maharashtra', maleWtKg: '400-450', femaleWtKg: '350-400', singleTwinPct: '95/5', purposes: 'Milk + Draught', suitableClimate: 'Maharashtra; semi-arid', note: 'Nagpuri is a long-horned black buffalo of the Vidarbha region used for both milk and field work. It is hardy and well adapted to the black cotton soil tracts of central India.' },
  { id: 'buffalo-pandharpuri', species: 'Buffalo', breed: 'Pandharpuri', origin: 'Sangli, Kolhapur - Maharashtra', maleWtKg: '400-450', femaleWtKg: '350-400', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Maharashtra; semi-arid', note: 'Pandharpuri buffalo has distinctive long, straight-to-curved horns and is reared mainly for milk. It is well adapted to the sugarcane belt of south-western Maharashtra.' },
  { id: 'buffalo-toda', species: 'Buffalo', breed: 'Toda', origin: 'Nilgiri hills - Tamil Nadu', maleWtKg: '350-400', femaleWtKg: '300-350', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Tamil Nadu; cool, hilly', note: 'Toda is a rare hill buffalo reared traditionally by the Toda tribe of the Nilgiris for milk and ritual use. It is a small, semi-wild population and is listed among India’s endangered livestock breeds.' },
  { id: 'buffalo-banni', species: 'Buffalo', breed: 'Banni', origin: 'Kutch - Gujarat', maleWtKg: '450-500', femaleWtKg: '400-450', singleTwinPct: '95/5', purposes: 'Milk', suitableClimate: 'Gujarat; arid, saline grasslands', note: 'Banni buffalo is a hardy, high-yielding breed of the Banni grasslands of Kutch, closely related to Kundhi. It withstands scarce water and saline pasture, making it well suited to extreme arid conditions.' },
  { id: 'sheep-marwari', species: 'Sheep', breed: 'Marwari', origin: 'Jodhpur, Pali, Nagaur, Barmer - Rajasthan', maleWtKg: '30-35', femaleWtKg: '25-30', singleTwinPct: '5/95 (mostly single)', purposes: 'Wool + Meat', suitableClimate: 'Rajasthan; arid, desert', note: 'Marwari is the most numerous sheep breed of Rajasthan, black-faced, reared under migratory grazing. It produces coarse carpet-grade wool and is also an important mutton breed of the desert tract.' },
  { id: 'sheep-magra', species: 'Sheep', breed: 'Magra', origin: 'Bikaner, Churu, Ganganagar - Rajasthan', maleWtKg: '30-35', femaleWtKg: '25-30', singleTwinPct: '10/90', purposes: 'Wool (superior carpet)', suitableClimate: 'Rajasthan; arid, desert', note: 'Magra sheep, a variety of Marwari, yields the best quality carpet wool in India, long and lustrous. It has a white body with a brown/black face and is reared by the Raika/Rebari pastoralist community.' },
  { id: 'sheep-chokla', species: 'Sheep', breed: 'Chokla', origin: 'Sikar, Churu, Jhunjhunu (Shekhawati region) - Rajasthan', maleWtKg: '30-32', femaleWtKg: '25-28', singleTwinPct: '10/90', purposes: 'Wool (fine, apparel-grade)', suitableClimate: 'Rajasthan; semi-arid', note: 'Chokla is prized for its fine, soft apparel-grade wool, considered among the best in the country. It has a brown/tan face and is reared mainly for wool with mutton as a secondary product.' },
  { id: 'sheep-nali', species: 'Sheep', breed: 'Nali', origin: 'Sri Ganganagar, Hanumangarh, Churu - Rajasthan', maleWtKg: '32-35', femaleWtKg: '28-30', singleTwinPct: '8/92', purposes: 'Wool (carpet)', suitableClimate: 'Rajasthan, Haryana; semi-arid, irrigated tracts', note: 'Nali is a large, white, Roman-nosed sheep adapted to the canal-irrigated areas of north Rajasthan. It produces medium carpet-grade wool and grows relatively fast, aiding mutton production too.' },
  { id: 'sheep-jaisalmeri', species: 'Sheep', breed: 'Jaisalmeri', origin: 'Jaisalmer, Barmer - Rajasthan', maleWtKg: '30-35', femaleWtKg: '25-30', singleTwinPct: '5/95', purposes: 'Wool + Meat', suitableClimate: 'Rajasthan; extreme arid, desert', note: 'Jaisalmeri is a hardy desert breed with a distinctive Roman nose and pendulous ears, well suited to scarce forage. It is reared mainly for coarse wool and mutton by pastoralists of the western Thar desert.' },
  { id: 'sheep-malpura', species: 'Sheep', breed: 'Malpura', origin: 'Tonk, Jaipur, Sawai Madhopur - Rajasthan', maleWtKg: '35-40', femaleWtKg: '28-32', singleTwinPct: '5/95', purposes: 'Meat', suitableClimate: 'Rajasthan; semi-arid', note: 'Malpura is a hair-type mutton breed with sparse coarse wool, valued for fast growth and good carcass quality. It is one of the important meat breeds of the semi-arid plains of eastern Rajasthan.' },
  { id: 'sheep-sonadi-chanothar', species: 'Sheep', breed: 'Sonadi (Chanothar)', origin: 'Udaipur, Chittorgarh, Bhilwara - Rajasthan', maleWtKg: '28-32', femaleWtKg: '22-26', singleTwinPct: '5/95', purposes: 'Meat + Coarse Wool', suitableClimate: 'Rajasthan; sub-humid, hilly (Mewar)', note: 'Sonadi is a small, tan-coloured breed of the hilly Mewar region reared mainly by the Gujjar community. It yields coarse wool but is more valued for mutton under low-input hilly grazing systems.' },
  { id: 'sheep-pugal', species: 'Sheep', breed: 'Pugal', origin: 'Bikaner, Sri Ganganagar - Rajasthan (Pugal region)', maleWtKg: '30-35', femaleWtKg: '25-28', singleTwinPct: '5/95', purposes: 'Wool + Meat', suitableClimate: 'Rajasthan; extreme arid, desert', note: 'Pugal is a hardy desert breed adapted to the harshest arid tracts bordering the Thar desert. It is reared for coarse carpet wool along with mutton under extensive pastoral systems.' },
  { id: 'sheep-muzaffarnagri', species: 'Sheep', breed: 'Muzaffarnagri', origin: 'Muzaffarnagar, Saharanpur, Bijnor - Uttar Pradesh', maleWtKg: '40-45', femaleWtKg: '32-35', singleTwinPct: '10/90', purposes: 'Meat', suitableClimate: 'Uttar Pradesh; sub-tropical, sub-humid', note: 'Muzaffarnagri is a large mutton breed with a Roman nose, among the biggest sheep breeds of North India. Wool is coarse and of low value; the breed is kept mainly for its fast-growing, heavy lambs.' },
  { id: 'sheep-deccani', species: 'Sheep', breed: 'Deccani', origin: 'Maharashtra, northern Karnataka', maleWtKg: '30-35', femaleWtKg: '25-28', singleTwinPct: '10/90', purposes: 'Meat + Coarse Wool', suitableClimate: 'Maharashtra, Karnataka; semi-arid Deccan plateau', note: 'Deccani is a hardy, mostly black, non-descript breed widely spread across the Deccan plateau. It is reared under migratory grazing mainly for mutton, with coarse wool as a by-product.' },
  { id: 'sheep-nellore', species: 'Sheep', breed: 'Nellore', origin: 'Nellore, Prakasam, Ongole - Andhra Pradesh', maleWtKg: '35-40', femaleWtKg: '28-32', singleTwinPct: '5/95', purposes: 'Meat', suitableClimate: 'Andhra Pradesh; hot, coastal', note: 'Nellore is a tall, leggy hair sheep (no wool cover) reared purely for mutton production. It is well adapted to hot, humid coastal Andhra Pradesh and is a fast-growing meat breed.' },
  { id: 'sheep-gaddi', species: 'Sheep', breed: 'Gaddi', origin: 'Chamba, Kangra - Himachal Pradesh', maleWtKg: '30-35', femaleWtKg: '25-28', singleTwinPct: '5/95', purposes: 'Wool', suitableClimate: 'Himachal Pradesh; cold, hilly/temperate', note: 'Gaddi sheep is reared by the transhumant Gaddi tribe, migrating between hills and high alpine pastures. It produces medium-fine wool and is well suited to cold, mountainous terrain.' },
  { id: 'sheep-patanwadi', species: 'Sheep', breed: 'Patanwadi', origin: 'Kutch, Saurashtra - Gujarat', maleWtKg: '30-35', femaleWtKg: '25-28', singleTwinPct: '5/95', purposes: 'Wool + Meat', suitableClimate: 'Gujarat; semi-arid', note: 'Patanwadi is a white sheep of Saurashtra with medium quality wool, closely related to Marwari. It is reared for both wool and mutton under extensive grazing in Gujarat’s semi-arid tracts.' },
  { id: 'goat-sirohi', species: 'Goat', breed: 'Sirohi', origin: 'Sirohi, Pali, Jalore - Rajasthan', maleWtKg: '45-50', femaleWtKg: '30-35', singleTwinPct: '40/60', purposes: 'Dual (Meat + Milk) / Breeder', suitableClimate: 'Rajasthan; hot, semi-arid', note: 'Sirohi is a dual-purpose breed of southern Rajasthan reared for both meat and milk in equal importance. It is medium-sized, brown with white patches, and well suited to the hot, dry climate of Rajasthan/Gujarat.' },
  { id: 'goat-marwari', species: 'Goat', breed: 'Marwari', origin: 'Jodhpur, Barmer, Nagaur - Rajasthan', maleWtKg: '35-40', femaleWtKg: '25-28', singleTwinPct: '30/70', purposes: 'Meat', suitableClimate: 'Rajasthan; arid, desert', note: 'Marwari goat is a hardy black desert breed reared under migratory herding across western Rajasthan. It is valued for meat and skin, and tolerates extreme heat and scarce fodder very well.' },
  { id: 'goat-jamunapari', species: 'Goat', breed: 'Jamunapari', origin: 'Etawah, Mathura - Uttar Pradesh', maleWtKg: '55-65', femaleWtKg: '40-45', singleTwinPct: '10/90 (mostly single)', purposes: 'Dual (Milk + Meat) / Breeder', suitableClimate: 'Uttar Pradesh; sub-tropical', note: 'Jamunapari is the tallest Indian goat breed with a distinctive Roman nose and long pendulous ears. It is an excellent milk breed and is widely exported for upgrading local goats in many countries.' },
  { id: 'goat-barbari', species: 'Goat', breed: 'Barbari', origin: 'Agra, Mathura, Etawah - Uttar Pradesh', maleWtKg: '30-35', femaleWtKg: '22-25', singleTwinPct: '50/50', purposes: 'Milk (Breeder)', suitableClimate: 'Uttar Pradesh; sub-tropical', note: 'Barbari is a small, compact, white-spotted breed known for high prolificacy and good milk quality. It reaches puberty early and is a popular breed for intensive stall-fed dairy-cum-meat units.' },
  { id: 'goat-beetal', species: 'Goat', breed: 'Beetal', origin: 'Gurdaspur, Amritsar - Punjab', maleWtKg: '50-55', femaleWtKg: '35-40', singleTwinPct: '30/70', purposes: 'Dual (Milk + Meat) / Breeder', suitableClimate: 'Punjab; sub-tropical', note: 'Beetal resembles Jamunapari with a Roman nose and long ears but is comparatively shorter in stature. It is a good dairy breed of Punjab, also used for upgrading local goats in the region.' },
  { id: 'goat-jakhrana', species: 'Goat', breed: 'Jakhrana', origin: 'Alwar, Jaipur - Rajasthan', maleWtKg: '45-50', femaleWtKg: '32-38', singleTwinPct: '20/80', purposes: 'Milk', suitableClimate: 'Rajasthan; semi-arid', note: 'Jakhrana is a high milk-yielding breed of north-eastern Rajasthan, black with white markings on ears/legs. It is increasingly favoured for commercial dairy goat farming due to its good udder conformation.' },
  { id: 'goat-osmanabadi', species: 'Goat', breed: 'Osmanabadi', origin: 'Osmanabad, Latur - Maharashtra', maleWtKg: '30-35', femaleWtKg: '22-26', singleTwinPct: '20/80', purposes: 'Meat (Breeder)', suitableClimate: 'Maharashtra; semi-arid', note: 'Osmanabadi is a prolific, mostly black breed of Marathwada reared primarily for meat production. It adapts well to varied climates and is commonly used as a base breed in crossbreeding for meat.' },
  { id: 'goat-black-bengal', species: 'Goat', breed: 'Black Bengal', origin: 'West Bengal, Bihar, Odisha border', maleWtKg: '12-16', femaleWtKg: '10-14', singleTwinPct: '5/60/35 (twin/triplet common)', purposes: 'Meat (skin/Breeder)', suitableClimate: 'Eastern India; hot, humid', note: 'Black Bengal is a small, highly prolific breed famous for superior quality skin and tasty, tender meat. It frequently produces twins or triplets and matures early, making it ideal for small backyard units.' },
  { id: 'goat-kutchi-kachchhi', species: 'Goat', breed: 'Kutchi (Kachchhi)', origin: 'Kutch - Gujarat', maleWtKg: '40-45', femaleWtKg: '28-32', singleTwinPct: '20/80', purposes: 'Meat + Draught', suitableClimate: 'Gujarat; arid', note: 'Kutchi goat is a large, hardy breed of Kutch used for meat and, traditionally, light pack/draught work. It is well adapted to the arid and saline grazing conditions of the Kutch region.' },
  { id: 'goat-malabari-tellicherry', species: 'Goat', breed: 'Malabari (Tellicherry)', origin: 'Kozhikode, Kannur (Malabar) - Kerala', maleWtKg: '30-35', femaleWtKg: '22-26', singleTwinPct: '30/70', purposes: 'Dual (Milk + Meat)', suitableClimate: 'Kerala; hot, humid', note: 'Malabari is a variable-coloured dual-purpose breed of Kerala with good adaptability to humid climates. It is popular with small farmers for both home milk consumption and meat sale.' },
  { id: 'pig-ghungroo', species: 'Pig', breed: 'Ghungroo', origin: 'West Bengal (Darjeeling terai)', maleWtKg: '55-65 (adult)', femaleWtKg: '45-55 (adult)', singleTwinPct: '60/40 (large litters, 6-8 piglets)', purposes: 'Meat (Breeder)', suitableClimate: 'West Bengal, Eastern India; humid sub-tropical', note: 'Ghungroo is a black, medium-sized indigenous pig noted for high prolificacy and good mothering ability. It is well adapted to backyard scavenging systems of eastern India’s humid climate.' },
  { id: 'pig-doom', species: 'Pig', breed: 'Doom', origin: 'Assam', maleWtKg: '50-60', femaleWtKg: '40-50', singleTwinPct: 'large litters (6-8 piglets)', purposes: 'Meat', suitableClimate: 'Assam, North-East India; humid, high rainfall', note: 'Doom is a hardy indigenous pig of Assam reared traditionally under low-input backyard systems. It is well suited to the high-rainfall, humid conditions of the Brahmaputra valley.' },
  { id: 'pig-niang-megha', species: 'Pig', breed: 'Niang Megha', origin: 'Meghalaya', maleWtKg: '50-55', femaleWtKg: '40-45', singleTwinPct: 'large litters (6-8 piglets)', purposes: 'Meat', suitableClimate: 'Meghalaya; cool, humid hilly', note: 'Niang Megha is an indigenous hill pig of Meghalaya, adapted to cool, humid mountainous conditions. It is reared extensively by tribal farmers mainly for local meat consumption.' },
  { id: 'pig-large-white-yorkshire-exotic', species: 'Pig', breed: 'Large White Yorkshire (exotic)', origin: 'Yorkshire, England; widely reared across India', maleWtKg: '250-300', femaleWtKg: '180-220', singleTwinPct: 'large litters (8-12 piglets)', purposes: 'Meat / Breeder (sire line)', suitableClimate: 'Pan-India (organised farms); needs housing', note: 'Large White Yorkshire is the most popular exotic breed used for crossbreeding to boost growth rate and litter size. It requires better housing/feeding than desi pigs but gives much faster weight gain.' },
  { id: 'poultry-aseel', species: 'Poultry', breed: 'Aseel', origin: 'Andhra Pradesh, Telangana', maleWtKg: '2.5-3.5', femaleWtKg: '2-2.5', singleTwinPct: 'clutch of 8-10 eggs, poor sitter/layer', purposes: 'Meat (fighting bird)', suitableClimate: 'Andhra Pradesh, Telangana; hot, tropical', note: 'Aseel is a strong, muscular game bird historically bred for cock-fighting, with excellent meat quality. It is a poor egg layer but is used as a base breed for improving meat qualities of desi fowl.' },
  { id: 'poultry-kadaknath', species: 'Poultry', breed: 'Kadaknath', origin: 'Jhabua, Dhar - Madhya Pradesh', maleWtKg: '1.5-2.0', femaleWtKg: '1.0-1.5', singleTwinPct: 'clutch of 8-10 eggs', purposes: 'Meat (black meat, medicinal)', suitableClimate: 'Madhya Pradesh, Rajasthan (tribal belt); semi-arid', note: 'Kadaknath is famous for its black meat, skin and bones, believed to have high nutritional/medicinal value. It commands premium prices and is increasingly popular for backyard poultry programmes.' },
  { id: 'poultry-chittagong', species: 'Poultry', breed: 'Chittagong', origin: 'Assam, North-East India', maleWtKg: '4.0-5.0', femaleWtKg: '3.0-3.5', singleTwinPct: 'clutch of 6-8 eggs, poor layer', purposes: 'Meat (large body)', suitableClimate: 'Assam, NE India; humid, high rainfall', note: 'Chittagong is one of the largest native fowl breeds, valued mainly for its meat and body size. It is docile in temperament and used to improve body weight in local crossbred flocks.' },
  { id: 'poultry-busra', species: 'Poultry', breed: 'Busra', origin: 'Punjab', maleWtKg: '2.0-2.5', femaleWtKg: '1.5-2.0', singleTwinPct: 'clutch of 10-12 eggs', purposes: 'Egg + Meat (dual)', suitableClimate: 'Punjab; sub-tropical', note: 'Busra is a dual-purpose desi breed of Punjab kept for both moderate egg production and meat. It is hardy and well suited to free-range backyard rearing conditions.' },
  { id: 'poultry-nicobari', species: 'Poultry', breed: 'Nicobari', origin: 'Andaman & Nicobar Islands', maleWtKg: '1.5-2.0', femaleWtKg: '1.2-1.5', singleTwinPct: 'clutch of 10-14 eggs, good layer among desi', purposes: 'Egg (dual)', suitableClimate: 'Andaman & Nicobar; hot, humid island climate', note: 'Nicobari fowl is one of the better egg-laying indigenous breeds, hardy under humid island conditions. It shows good disease resistance and is used in breeding programmes to improve desi layers.' },
  { id: 'poultry-punjab-brown', species: 'Poultry', breed: 'Punjab Brown', origin: 'Punjab', maleWtKg: '2.0-2.5', femaleWtKg: '1.5-2.0', singleTwinPct: 'clutch of 10-12 eggs', purposes: 'Egg + Meat (dual)', suitableClimate: 'Punjab; sub-tropical', note: 'Punjab Brown is a hardy dual-purpose desi bird developed for village conditions of Punjab. It combines reasonable egg production with acceptable meat quality on low-input feeding.' },
  { id: 'poultry-white-leghorn-exotic', species: 'Poultry', breed: 'White Leghorn (exotic)', origin: 'Livorno, Italy; widely reared across India', maleWtKg: '2.0-2.5', femaleWtKg: '1.5-2.0', singleTwinPct: 'commercial layer, 280-300 eggs/year', purposes: 'Egg (commercial layer)', suitableClimate: 'Pan-India (organised poultry farms); needs housing', note: 'White Leghorn is the world’s leading commercial egg-laying breed, white-plumaged with high feed efficiency. It is the standard layer strain used in India’s organised commercial egg industry.' },
  { id: 'horse-marwari', species: 'Horse', breed: 'Marwari', origin: 'Jodhpur, Pali region - Rajasthan', maleWtKg: '350-400', femaleWtKg: '300-350', singleTwinPct: 'single (rarely twin)', purposes: 'Riding / Breeder', suitableClimate: 'Rajasthan; hot, arid', note: 'Marwari horse is famous for its distinctive inward-curving ear tips and is a prized riding/ceremonial breed. It is hardy, agile, and well adapted to the hot, arid climate of the Marwar region.' },
  { id: 'horse-kathiawari', species: 'Horse', breed: 'Kathiawari', origin: 'Kathiawar peninsula, Junagadh - Gujarat', maleWtKg: '300-350', femaleWtKg: '280-320', singleTwinPct: 'single', purposes: 'Riding / Breeder', suitableClimate: 'Gujarat; hot, semi-arid coastal', note: 'Kathiawari, closely related to Marwari, also has curved ear tips and is known for great stamina. It is a hardy desert-adapted riding breed traditionally used by Rajput cavalry.' },
  { id: 'horse-manipuri-pony', species: 'Horse', breed: 'Manipuri (Pony)', origin: 'Manipur', maleWtKg: '200-250', femaleWtKg: '180-220', singleTwinPct: 'single', purposes: 'Riding / Sport (polo origin)', suitableClimate: 'Manipur, North-East India; humid sub-tropical', note: 'Manipuri pony is small but strong and agile, historically regarded as the origin of modern polo. It is well adapted to the humid hill terrain of Manipur and used for riding and light draught.' },
  { id: 'horse-spiti-pony', species: 'Horse', breed: 'Spiti (Pony)', origin: 'Spiti valley - Himachal Pradesh', maleWtKg: '200-250', femaleWtKg: '180-220', singleTwinPct: 'single', purposes: 'Pack / Riding', suitableClimate: 'Himachal Pradesh; cold, high-altitude', note: 'Spiti pony is a small, sturdy mountain breed used mainly as a pack animal in the high Himalayas. It withstands extreme cold and thin mountain air of the trans-Himalayan Spiti valley very well.' },
  { id: 'horse-bhutia-pony', species: 'Horse', breed: 'Bhutia (Pony)', origin: 'Sikkim, Darjeeling hills - West Bengal', maleWtKg: '220-260', femaleWtKg: '200-240', singleTwinPct: 'single', purposes: 'Pack / Riding', suitableClimate: 'Sikkim, West Bengal hills; cold, hilly', note: 'Bhutia pony is a hardy hill pony traditionally used for carrying loads on steep Himalayan trails. It is surefooted and well suited to cold, mountainous terrain of the eastern Himalayas.' },
  { id: 'horse-zanskari-pony', species: 'Horse', breed: 'Zanskari (Pony)', origin: 'Zanskar valley - Ladakh', maleWtKg: '200-250', femaleWtKg: '180-220', singleTwinPct: 'single', purposes: 'Pack / Riding', suitableClimate: 'Ladakh; cold desert, high-altitude', note: 'Zanskari pony is exceptionally hardy, adapted to the cold desert and high-altitude terrain of Ladakh. It is used mainly as a pack animal by local communities in extremely harsh climatic conditions.' },
 ];
export function breedsOf(species: LivestockSpecies): BreedRecord[] {
  return BREED_MASTER.filter(function (b) { return b.species === species; });
}
export function findBreed(species: string, breed: string): BreedRecord | undefined {
  return BREED_MASTER.find(function (b) { return b.species === species && b.breed === breed; });
}