// Auto-generated from Livestock_Breed_Master 01.xlsx (Techno-Defaults). Ranges are textbook averages; engine uses locked singles.
export interface TechnoDefaults {
  animal: string; pubertyMale: string; pubertyFemale: string; firstBreeding: string; gestation: string; parturitionInterval: string; fertilityPct: string; litterSize: string; sexRatio: string; youngMortality: string; adultMortality: string; saleAge: string; greenFodder: string; dryFodder: string; concentrate: string; coveredMale: string; coveredFemale: string; openMale: string; openFemale: string; water: string; manure: string;
}
export const TECHNO_DEFAULTS: TechnoDefaults[] = [
  { animal: 'Cattle (Indigenous Dairy/Dual, e.g., Gir, Sahiwal, Tharparkar)', pubertyMale: '24-30 months', pubertyFemale: '24-30 months', firstBreeding: '30-36 months', gestation: '280-285 days', parturitionInterval: '13-15 months', fertilityPct: '65-70%', litterSize: '1 (twinning <2%)', sexRatio: '1 : 25-30', youngMortality: '8-10%', adultMortality: '2-4%', saleAge: 'Surplus male calf: 1-1.5 yrs; culled cow: 8-10 yrs', greenFodder: '15-20 kg', dryFodder: '5-6 kg', concentrate: '1.5-6 kg (per 2.5 L milk above maintenance)', coveredMale: '40 sq.ft', coveredFemale: '35 sq.ft', openMale: '80 sq.ft', openFemale: '70 sq.ft', water: '40-50 L (up to 70 L lactating)', manure: '10-15 kg' },
  { animal: 'Buffalo (Murrah, Nili-Ravi, Jaffarabadi, Mehsana, Surti)', pubertyMale: '30-36 months', pubertyFemale: '30-36 months', firstBreeding: '36-42 months', gestation: '310-315 days', parturitionInterval: '15-18 months', fertilityPct: '60-65%', litterSize: '1 (twinning rare)', sexRatio: '1 : 20-25', youngMortality: '10-12%', adultMortality: '3-5%', saleAge: 'Surplus male calf: 1.5-2 yrs; culled female: 10-12 yrs', greenFodder: '20-25 kg', dryFodder: '6-7 kg', concentrate: '2-7 kg (per 2 L milk above maintenance)', coveredMale: '45 sq.ft', coveredFemale: '40 sq.ft', openMale: '90 sq.ft', openFemale: '80 sq.ft', water: '50-60 L + wallow water', manure: '12-18 kg' },
  { animal: 'Sheep (Marwari, Chokla, Nali, Malpura, Muzaffarnagri, etc.)', pubertyMale: '6-8 months', pubertyFemale: '7-9 months', firstBreeding: '12-18 months', gestation: '144-152 days (~5 months)', parturitionInterval: '8 months (intensive) / 12 months (extensive)', fertilityPct: '100-125%', litterSize: '1.0-1.2', sexRatio: '1 : 20-25', youngMortality: '10-15%', adultMortality: '3-5%', saleAge: '8-10 months (~25-30 kg body wt)', greenFodder: '3-4 kg (mainly grazing)', dryFodder: '1-1.5 kg', concentrate: '0.2-0.3 kg (lactating ewe/fattening lamb)', coveredMale: '12 sq.ft', coveredFemale: '10 sq.ft', openMale: '20 sq.ft', openFemale: '15 sq.ft', water: '3-4 L', manure: '1-1.5 kg' },
  { animal: 'Goat (Sirohi, Jamunapari, Barbari, Beetal, Black Bengal, etc.)', pubertyMale: '6-8 months', pubertyFemale: '7-10 months', firstBreeding: '12-15 months', gestation: '145-150 days', parturitionInterval: '8 months (intensive) / 12 months (extensive)', fertilityPct: '150-180%', litterSize: '1.5-2.0 (twins/triplets common)', sexRatio: '1 : 20-25', youngMortality: '15-20%', adultMortality: '3-5%', saleAge: '8-10 months (~20-25 kg body wt)', greenFodder: '3-4 kg (browse/grazing)', dryFodder: '1-1.5 kg', concentrate: '0.2-0.3 kg', coveredMale: '10 sq.ft', coveredFemale: '8 sq.ft', openMale: '15 sq.ft', openFemale: '12 sq.ft', water: '3-4 L', manure: '1-1.5 kg' },
  { animal: 'Pig (Ghungroo, Doom, Niang Megha, Large White Yorkshire)', pubertyMale: '6-8 months (boar)', pubertyFemale: '6-8 months (gilt)', firstBreeding: '8-9 months (~90-100 kg exotic; earlier in desi)', gestation: '112-115 days (~3 yrs 3 mo. 3 wk. rule of thumb)', parturitionInterval: '6 months (2 litters/year)', fertilityPct: '180-200% (litters/sow/year)', litterSize: '6-8 (desi); 8-12 (exotic e.g. Large White Yorkshire)', sexRatio: '1 : 10-15', youngMortality: '15-20% (pre-weaning)', adultMortality: '3-5%', saleAge: '8-10 months (~80-100 kg market wt.)', greenFodder: '2-3 kg (greens/kitchen waste supplement)', dryFodder: 'Minimal/not a major component', concentrate: '1.5-2.5 kg (up to 2-3 kg for lactating sow)', coveredMale: '30 sq.ft (boar)', coveredFemale: '25 sq.ft (sow)', openMale: '20 sq.ft', openFemale: '15 sq.ft', water: '10-15 L (20-25 L lactating sow)', manure: '2-3 kg' },
  { animal: 'Horse (Marwari, Kathiawari, Manipuri, Spiti, Bhutia, Zanskari)', pubertyMale: '12-15 months', pubertyFemale: '12-15 months', firstBreeding: '3-4 years', gestation: '330-345 days (~11 months)', parturitionInterval: '12 months (ideal); 18-24 months (practical)', fertilityPct: '60-70%', litterSize: '1 (twinning <1-2%)', sexRatio: '1 : 15-20', youngMortality: '8-10% (foal)', adultMortality: '2-3%', saleAge: '3-4 years (trained riding animal, max. value)', greenFodder: '8-10 kg', dryFodder: '4-5 kg', concentrate: '2-4 kg (working animal)', coveredMale: '100 sq.ft (stallion)', coveredFemale: '90 sq.ft (mare)', openMale: '300 sq.ft', openFemale: '250 sq.ft', water: '30-40 L', manure: '15-20 kg' },
  { animal: 'Poultry - General/Desi Backyard (Aseel, Kadaknath, Nicobari, Busra, etc.)', pubertyMale: '5-6 months (cockerel)', pubertyFemale: '5-6 months (pullet, point of lay)', firstBreeding: '5-6 months (point of lay)', gestation: '21 days (incubation)', parturitionInterval: 'Continuous laying (egg every 24-26 hrs); 1-2 broody clutches/year', fertilityPct: 'Hatchability 80-85%', litterSize: '8-12 eggs/clutch (broody desi hen)', sexRatio: '1 : 8-10 (natural mating)', youngMortality: '15-20% (chick)', adultMortality: '5-8% (annual, adult)', saleAge: '5-6 months (~1-1.5 kg) meat; hen culled after 2 laying cycles', greenFodder: 'Free-range/scavenging + 80-100 g grain/mash', dryFodder: 'Not applicable', concentrate: '100-120 g/bird (if fully fed, balanced ration)', coveredMale: '2-3 sq.ft/bird', coveredFemale: '2-3 sq.ft/bird', openMale: '4-5 sq.ft/bird (free-range)', openFemale: '4-5 sq.ft/bird (free-range)', water: '200-250 ml/bird', manure: '40-50 g/bird' },
 ];
export function technoOf(animal: string): TechnoDefaults | undefined {
  return TECHNO_DEFAULTS.find(function (t) {
    return t.animal === animal || t.animal.indexOf(animal + ' ') === 0 || t.animal.indexOf(animal + ' (') === 0;
  });
}