// Auto-generated from Animal_Husbandry_Schemes_Central_Rajasthan.xlsx. Verify current guidelines at dahd.gov.in before official use.
export interface SchemeRecord {
  id: string; level: string; name: string; focus: string; details: string; department: string;
}
export const SCHEME_MASTER: SchemeRecord[] = [
  { id: 'central-0', level: 'Central', name: 'Rashtriya Gokul Mission (RGM)', focus: 'Breeding / Production', details: 'Development and conservation of indigenous bovine breeds, genetic upgradation through nationwide Artificial Insemination coverage, progeny testing and pedigree selection, and establishment of Gokul Grams/breeding farms to enhance milk production and productivity.', department: 'Department of Animal Husbandry & Dairying (DAHD), Ministry of Fisheries, Animal Husbandry and Dairying, GoI (through State AH Departments)' },
  { id: 'central-1', level: 'Central', name: 'National Programme for Dairy Development (NPDD)', focus: 'Processing / Production', details: 'Strengthening of village-level milk procurement infrastructure, milk testing quality equipment, and cooperative/producer-company dairy infrastructure to improve rural milk marketing.', department: 'DAHD, GoI — implemented via State Dairy Cooperative Federations/NDDB' },
  { id: 'central-2', level: 'Central', name: 'National Livestock Mission (NLM)', focus: 'Entrepreneurial / Breeding / Extension', details: 'Umbrella mission with sub-components for Livestock Development (poultry, sheep-goat, piggery breed improvement), Feed & Fodder Development, and an Entrepreneurship Development Programme offering capital-subsidy-linked bank loans for setting up commercial rearing/hatchery/feed units.', department: 'DAHD, GoI (through State AH Departments and lending banks/NABARD)' },
  { id: 'central-3', level: 'Central', name: 'Livestock Health and Disease Control Programme (LH&DC)', focus: 'Research / Extension (Animal Health)', details: 'Merged scheme covering nationwide vaccination against Foot & Mouth Disease and Brucellosis (erstwhile NADCP), Assistance to States for Control of Animal Diseases (ASCAD), disease surveillance (NADRS), and strengthening of veterinary hospitals/mobile veterinary units.', department: 'DAHD, GoI (through State Animal Husbandry/Veterinary Departments)' },
  { id: 'central-4', level: 'Central', name: 'Animal Husbandry Infrastructure Development Fund (AHIDF)', focus: 'Processing / Entrepreneurial', details: 'Interest-subvented loans to individuals, FPOs, private companies, MSMEs and cooperatives for setting up dairy/meat processing units, animal feed plants and breed multiplication/hatchery farms.', department: 'DAHD, GoI — implemented through NABARD, NCDC and scheduled banks' },
  { id: 'central-5', level: 'Central', name: 'Dairy Infrastructure Development (under Infrastructure Development Fund)', focus: 'Processing', details: 'Modernisation and creation of milk chilling, processing and value-addition infrastructure for dairy cooperatives and producer institutions (successor to erstwhile DIDF).', department: 'DAHD, GoI — implemented through NDDB/NCDC' },
  { id: 'central-6', level: 'Central', name: 'Livestock Census & Integrated Sample Survey', focus: 'Research', details: 'Quinquennial livestock census and annual sample surveys estimating milk, egg, meat and wool production for planning and monitoring of the sector.', department: 'DAHD, GoI (in coordination with State AH Departments)' },
  { id: 'central-7', level: 'Central', name: 'Rural Backyard Poultry Development (component of NLM)', focus: 'Extension / Entrepreneurial', details: 'Distribution of improved dual-purpose poultry chicks/units to rural and BPL households to supplement household income and nutrition.', department: 'DAHD, GoI (through State Poultry Development Corporations/AH Departments)' },
  { id: 'central-8', level: 'Central', name: 'Poultry/Sheep-Goat/Piggery Entrepreneurship (component of NLM-EDP)', focus: 'Entrepreneurial / Breeding', details: 'Back-ended capital subsidy for setting up commercial layer/broiler units, sheep-goat breeding farms and piggery units through bank-linked term loans.', department: 'DAHD, GoI (through NABARD/State AH Departments and banks)' },
  { id: 'central-9', level: 'Central', name: 'Fodder and Feed Development (Sub-Mission under NLM)', focus: 'Production', details: 'Support for fodder seed production and processing units, silage-making units, feed analysis laboratories and area-specific mineral mixture plants.', department: 'DAHD, GoI (through State AH/Animal Husbandry Departments)' },
  { id: 'central-10', level: 'Central', name: 'Pashu Kisan Credit Card (under Kisan Credit Card scheme)', focus: 'Entrepreneurial', details: 'Short-term working-capital credit at concessional interest for meeting the operational needs of dairy and livestock farmers.', department: 'Department of Financial Services & DAHD, GoI — implemented through banks' },
  { id: 'central-11', level: 'Central', name: 'Livestock Insurance (component of NLM)', focus: 'Entrepreneurial / Risk Mitigation', details: 'Subsidised premium for insuring cattle, buffalo, sheep, goat, pig and poultry against death, to protect farmers from financial loss.', department: 'DAHD, GoI (through State AH Departments and insurance companies)' },
  { id: 'state-12', level: 'State', name: 'Mukhyamantri Mangla Pashu Bima Yojana', focus: 'Welfare / Insurance', details: 'Free/subsidised livestock insurance cover for cattle, buffalo, sheep, goat and camel to provide financial security to livestock owners against animal death.', department: 'Animal Husbandry Department, Government of Rajasthan' },
  { id: 'state-13', level: 'State', name: 'Pashudhan Nishulk Aarogya Yojna (PNAY)', focus: 'Extension (Animal Health)', details: 'Free distribution of essential medicines at veterinary institutions and health camps to reduce treatment cost and mortality of sick animals; launched 15 August 2012.', department: 'Animal Husbandry Department, Government of Rajasthan' },
  { id: 'state-14', level: 'State', name: 'Camel Conservation Scheme (Ushtra Vikas Yojana)', focus: 'Breeding / Entrepreneurial', details: 'Financial assistance for camel rearing and conservation to arrest the declining camel population, including support for camel-based product/milk processing units; started under CM Budget Announcement 2022-23.', department: 'Animal Husbandry Department, Government of Rajasthan' },
  { id: 'state-15', level: 'State', name: 'Breed Improvement through Artificial Insemination (BITAI)', focus: 'Breeding', details: 'Doorstep AI services and expansion of AI coverage using high genetic merit/sexed semen for conservation and genetic upgradation of indigenous cattle and buffalo breeds.', department: 'Animal Husbandry Department, Government of Rajasthan' },
  { id: 'state-16', level: 'State', name: 'High Genetic Merit (HGM) Bull Production Scheme (under RKVY)', focus: 'Breeding', details: 'Production of elite pedigree-selected bulls of indigenous breeds (e.g., Tharparkar, Rathi, Gir) for natural service and semen stations to improve herd genetics.', department: 'Animal Husbandry Department, Government of Rajasthan (RKVY-funded)' },
  { id: 'state-17', level: 'State', name: 'Go-Kaashth Yojana', focus: 'Processing / Entrepreneurial', details: 'Support for processing cow dung into an eco-friendly wood substitute (Go-Kaashth) at large registered gaushalas maintaining more than 1,000 cattle, generating additional gaushala income.', department: 'Directorate of Gopalan, Government of Rajasthan' },
  { id: 'state-18', level: 'State', name: 'Grant-in-Aid to Gaushalas (Cow Conservation & Promotion Fund)', focus: 'Production / Welfare', details: 'Financial assistance for feed, fodder and maintenance of destitute cattle housed in registered gaushalas and Kanji Houses, under the Cow Conservation and Promotion Fund Rules.', department: 'Directorate of Gopalan, Government of Rajasthan' },
  { id: 'state-19', level: 'State', name: 'Panchayat Samiti Nandishala Jan Sahbhagita Yojana', focus: 'Production / Infrastructure', details: 'Construction of shelters (Nandishalas) for destitute male cattle in every Panchayat Samiti, with the State bearing 90% of construction cost under public participation.', department: 'Animal Husbandry Department & Panchayati Raj Department, Government of Rajasthan' },
  { id: 'state-20', level: 'State', name: 'State-share support under National Livestock Mission (Sheep-Goat/Poultry/Piggery units)', focus: 'Entrepreneurial / Breeding', details: 'State matching support for setting up commercial sheep-goat, backyard poultry and piggery entrepreneurship units and fodder development activities under the central NLM framework.', department: 'Animal Husbandry Department, Government of Rajasthan' },
  { id: 'state-21', level: 'State', name: 'Mobile Veterinary Unit / Pashu Sanjeevani (Toll-Free Emergency Service)', focus: 'Extension', details: 'Doorstep emergency veterinary treatment for sick/injured livestock through a call-based mobile veterinary van service.', department: 'Animal Husbandry Department, Government of Rajasthan' },
  { id: 'state-22', level: 'State', name: 'Wool Development Scheme', focus: 'Processing / Extension', details: 'Support for sheep-wool grading, shearing training and marketing infrastructure to improve returns to sheep-wool producers in the state.', department: 'Animal Husbandry Department / Rajasthan State Wool Marketing Federation' },
 ];
export function schemesOf(level: string): SchemeRecord[] {
  return SCHEME_MASTER.filter(function (s) { return s.level === level; });
}
export function findScheme(name: string): SchemeRecord | undefined {
  return SCHEME_MASTER.find(function (s) { return s.name === name; });
}