export type BookEntry = { t: string; a: string; s: "open" | "ref" };
export type SubjectEntry = { subject: string; code: string; books: BookEntry[] };

export const CATALOG_DATA: SubjectEntry[] = [
  { subject:"Veterinary Anatomy", code:"VA", books:[
    {t:"Primary Veterinary Anatomy", a:"R.K. Ghosh", s:"ref"},
    {t:"Essentials of Veterinary Histology and Embryology", a:"R.K. Ghosh", s:"ref"},
    {t:"Veterinary Anatomy", a:"Various", s:"ref"},
    {t:"Applied Veterinary Anatomy", a:"Various", s:"ref"},
  ]},
  { subject:"Veterinary Physiology", code:"VP", books:[
    {t:"Veterinary Physiology", a:"TANUVAS", s:"open"},
    {t:"Dukes' Physiology of Domestic Animals", a:"W.O. Reece (ed.)", s:"ref"},
    {t:"Laboratory Manual for Comparative Veterinary Anatomy and Physiology", a:"P.E. Cochran", s:"ref"},
  ]},
  { subject:"Livestock Production Management", code:"LPM", books:[
    {t:"Farm Animal Management", a:"Rana Ranjeet Singh & Md Manzarul Islam", s:"ref"},
    {t:"A Textbook of Animal Husbandry", a:"G.C. Banerjee", s:"ref"},
    {t:"Livestock Production Management", a:"N.S.R. Sastry & C.K. Thomas", s:"ref"},
    {t:"Handbook of Good Dairy Husbandry Practices", a:"NDDB", s:"open"},
    {t:"Manual of Avian Production and Management", a:"Nilotpal Ghosh & Rajarshi Samanta", s:"ref"},
  ]},
  { subject:"Veterinary Microbiology", code:"VM", books:[
    {t:"Ananthanarayan and Paniker's Textbook of Microbiology", a:"Ananthanarayan & Paniker", s:"ref"},
    {t:"Veterinary Mycology", a:"Indranil Samanta", s:"ref"},
    {t:"Veterinary Microbiology", a:"TANUVAS", s:"open"},
    {t:"General and Systematic Veterinary Virology", a:"Various", s:"ref"},
    {t:"Veterinary Virology", a:"Various", s:"ref"},
    {t:"Veterinary Microbiology and Microbial Disease", a:"Blackwell Science", s:"ref"},
    {t:"Fundamentals of Veterinary Microbiology", a:"A.N. Rycroft", s:"ref"},
  ]},
  { subject:"Veterinary Pathology", code:"PAT", books:[
    {t:"Textbook of Veterinary Pathology, Quick Review and Self Assessment", a:"R.S. Chauhan", s:"ref"},
    {t:"A Textbook of Veterinary General Pathology", a:"J.L. Vegad", s:"ref"},
    {t:"A Textbook of Veterinary Systemic Pathology", a:"J.L. Vegad & Madhu Swamy", s:"ref"},
    {t:"A Textbook of Veterinary Special Pathology: Infectious Diseases of Livestock and Poultry", a:"J.L. Vegad & A.K. Katiyar", s:"ref"},
    {t:"Postmortem Examination and Veterolegal Cases", a:"Veterinary Council of India", s:"open"},
    {t:"Poultry Pathology", a:"J.L. Vegad", s:"ref"},
    {t:"Thomson's Special Veterinary Pathology", a:"Various", s:"ref"},
    {t:"Pathologic Basis of Veterinary Disease", a:"James F. Zachary", s:"ref"},
    {t:"Clinical Pathology and Laboratory Techniques for Veterinary Technicians", a:"Wiley Blackwell", s:"ref"},
  ]},
  { subject:"Veterinary Biochemistry", code:"BIO", books:[
    {t:"Biochemistry", a:"U. Satyanarayana & U. Chakrapani", s:"ref"},
  ]},
  { subject:"Animal Genetics and Breeding", code:"AGB", books:[
    {t:"Animal Husbandry Statistics and Computer Applications", a:"R. Thiagarajan", s:"ref"},
    {t:"Principles of Animal Genetics and Population Genetics", a:"R. Thiagarajan", s:"ref"},
    {t:"A Text Book on Animal Genetics", a:"P. Kanakaraj", s:"ref"},
  ]},
  { subject:"Animal Nutrition", code:"NUT", books:[
    {t:"Principles of Animal Nutrition and Feed Technology", a:"D.V. Reddy", s:"ref"},
    {t:"Applied Nutrition: Livestock, Poultry, Rabbits and Laboratory Animals", a:"D.V. Reddy", s:"ref"},
    {t:"Applied Nutrition: Cats, Dogs, Wild Animals and Birds", a:"D.V. Reddy", s:"ref"},
    {t:"Animal Nutrition and Product Quality Laboratory Manual", a:"ICARDA", s:"open"},
    {t:"Waltham Pocket Book of Essential Nutrition for Cats and Dogs", a:"Waltham", s:"ref"},
  ]},
  { subject:"Veterinary Parasitology", code:"PARA", books:[
    {t:"Veterinary Parasitology at a Glance", a:"S.C. Mandal", s:"ref"},
    {t:"Textbook of Veterinary Parasitology", a:"Bhatia, Pathak & Juyal", s:"ref"},
    {t:"Veterinary Parasitology", a:"Taylor, Coop & Wall", s:"ref"},
    {t:"Helminths, Arthropods and Protozoa of Domesticated Animals", a:"E.J.L. Soulsby", s:"ref"},
    {t:"Essentials of Veterinary Parasitology", a:"S. Pal & P.K. Sanyal", s:"ref"},
    {t:"Veterinary Clinical Parasitology", a:"Wiley Blackwell", s:"ref"},
    {t:"Veterinary Parasitology", a:"Various", s:"ref"},
  ]},
  { subject:"Veterinary Pharmacology and Toxicology", code:"PHARM", books:[
    {t:"Essentials of Medical Pharmacology", a:"K.D. Tripathi", s:"ref"},
    {t:"Essentials of Veterinary Pharmacology and Therapeutics", a:"Harpal Singh Sandhu", s:"ref"},
    {t:"Textbook of Veterinary Toxicology", a:"Harpal Singh Sandhu & Rajinder Singh Brar", s:"ref"},
    {t:"Synopsis of Veterinary Pharmacology and Toxicology", a:"V. Vani Prasad & K.M. Koley", s:"ref"},
    {t:"Veterinary Toxicology", a:"Radhey Mohan Tiwari & Malini Sinha", s:"ref"},
    {t:"Pharmacology Flashcards", a:"Baron & Lee", s:"ref"},
  ]},
  { subject:"Veterinary Public Health and Epidemiology", code:"VPH", books:[
    {t:"Elements of Veterinary Public Health", a:"ICAR", s:"open"},
    {t:"Veterinary Epidemiology", a:"Michael Thrusfield", s:"ref"},
    {t:"Textbook of Zoonoses", a:"J.S. Bedi, D. Vijay & P. Dhaka", s:"ref"},
    {t:"Veterinary Public Health and Epidemiology", a:"Krishna Gopal Narayan", s:"ref"},
  ]},
  { subject:"Vet. & Animal Husbandry Extension Education", code:"EXT", books:[
    {t:"Textbook of Animal Husbandry and Livestock Extension", a:"P. Mathialagan", s:"ref"},
  ]},
  { subject:"Livestock Products Technology", code:"LPT", books:[
    {t:"Meat & Meat Products Technology, Including Poultry Products Technology", a:"B.D. Sharma", s:"ref"},
    {t:"Modern Abattoir Practices and Animal Byproducts Technology", a:"B.D. Sharma", s:"ref"},
    {t:"Milk and Milk Products Technology", a:"Raziuddin & Hembade", s:"ref"},
    {t:"Lawrie's Meat Science", a:"Elsevier", s:"ref"},
    {t:"Outlines of Dairy Technology", a:"Sukumar De", s:"ref"},
  ]},
  { subject:"Veterinary Medicine", code:"MED", books:[
    {t:"Textbook of Clinical Veterinary Medicine", a:"Amalendu Chakrabarti", s:"ref"},
    {t:"A Textbook of Preventive Veterinary Medicine", a:"Amalendu Chakrabarti", s:"ref"},
    {t:"Textbook of Clinical Veterinary Medicine", a:"ICAR", s:"open"},
    {t:"Textbook of Preventive Veterinary Medicine and Epidemiology", a:"ICAR", s:"open"},
    {t:"Postmortem Examination and Veterolegal Cases", a:"Veterinary Council of India", s:"open"},
    {t:"Clinical Veterinary Medicine", a:"A.U. Bhikane", s:"ref"},
    {t:"Preventive Veterinary Medicine", a:"Various", s:"ref"},
    {t:"A Textbook of the Diseases of Cattle, Horses, Sheep, Pigs and Goats", a:"Elsevier", s:"ref"},
    {t:"Greene's Infectious Diseases of the Dog and Cat", a:"Elsevier", s:"ref"},
    {t:"Booklet of Important Poultry Diseases", a:"MSD Animal Health", s:"ref"},
    {t:"The Feline Patient", a:"Gary D. Norsworthy", s:"ref"},
    {t:"Veterinary Emergency and Critical Care Procedures", a:"Various", s:"ref"},
    {t:"Pocket Handbook of Small Animal Medicine", a:"Kit Sturgess", s:"ref"},
  ]},
  { subject:"Veterinary Surgery and Radiology", code:"SURG", books:[
    {t:"A Textbook on Veterinary Surgery and Radiology", a:"Samit Kumar Nandi, Samar Halder & Mozammel Hoque", s:"ref"},
    {t:"Ruminant Surgery", a:"R.P.S. Tyagi & Jit Singh", s:"ref"},
    {t:"Veterinary Surgery: Practical Guide", a:"P.B. Patel & A.M. Patel", s:"ref"},
    {t:"Zoo and Wild Animal Dentistry", a:"Emily & Eisner", s:"ref"},
    {t:"Veterinary Dentistry", a:"Matthew Lemmons", s:"ref"},
    {t:"Thrall's Textbook of Veterinary Diagnostic Radiology", a:"Various", s:"ref"},
    {t:"Abdominal Ultrasound in Cats and Dogs", a:"Various", s:"ref"},
    {t:"Barnett Veterinary Ophthalmology", a:"Keith Barnett", s:"ref"},
  ]},
  { subject:"Veterinary Gynaecology and Obstetrics", code:"GYN", books:[
    {t:"Veterinary Obstetrics and Genital Diseases", a:"S.J. Roberts", s:"ref"},
    {t:"Applied Veterinary Gynaecology and Obstetrics", a:"Pradeep Kumar", s:"ref"},
    {t:"Applied Veterinary Andrology and Artificial Insemination", a:"Pradeep Kumar", s:"ref"},
    {t:"Veterinary Andrology and Artificial Insemination", a:"M.S. Saxena", s:"ref"},
    {t:"Laboratory Manual on Animal Gynaecology", a:"S.K. Agarwal, U. Shanker & M.R. Ansari", s:"ref"},
    {t:"Reproductive Technologies in Animals", a:"Elsevier", s:"ref"},
    {t:"Handbook of Obstetrics", a:"Elsevier", s:"ref"},
  ]},
  { subject:"Reference Shelf & Field Notes", code:"REF", books:[
    {t:"Field Veterinarian Notes", a:"Various", s:"ref"},
    {t:"Veterinary Dictionary", a:"Various", s:"ref"},
    {t:"Animal Biotechnology Notes", a:"Various", s:"ref"},
    {t:"Handbook for Veterinary Clinicians", a:"Various", s:"ref"},
    {t:"A Guide to Disease Diagnosis", a:"Veterinary College, Hassan", s:"open"},
    {t:"Ultimate Veterinary Notes Bundle", a:"Nicole Cohen", s:"ref"},
    {t:"Animal Husbandry Statistics 2025", a:"Government of India", s:"open"},
    {t:"Guidelines for Minimum Standards of Veterinary Infrastructure in India", a:"Government of India", s:"open"},
  ]},
];
